# Generated by Django 5.2.7 on 2025-10-29 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'parent'], name='decks_user_id_6ebab0_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['parent'], name='decks_parent__34248d_idx'),
        ),
    ]
