# Generated by Django 5.2.7 on 2025-10-29 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0002_initial'),
        ('drop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drop',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='deck.deck'),
        ),
        migrations.AddField(
            model_name='drop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drop.drop'),
        ),
        migrations.AddField(
            model_name='tagdropmapping',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_drop_mappings', to='drop.drop'),
        ),
        migrations.AddField(
            model_name='tagdropmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_drop_mappings', to='drop.tag'),
        ),
        migrations.AddIndex(
            model_name='drop',
            index=models.Index(fields=['deck'], name='drops_deck_id_65f576_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['drop', 'parent'], name='comments_drop_id_89df97_idx'),
        ),
        migrations.AddIndex(
            model_name='tagdropmapping',
            index=models.Index(fields=['tag', 'drop'], name='tag_drop_ma_tag_id_cbba34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagdropmapping',
            unique_together={('tag', 'drop')},
        ),
    ]
