# Generated by Django 5.2.7 on 2025-10-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0002_tag_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDropMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_drop_mappings', to='drop.drop')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_drop_mappings', to='drop.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
