# Generated by Django 5.2.7 on 2025-10-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='meta_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='screenshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
